# Generated by Django 4.2.24 on 2025-10-13 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree', models.CharField(max_length=100)),
                ('shrub', models.CharField(max_length=100)),
                ('herbs', models.CharField(max_length=100)),
                ('creeper', models.CharField(max_length=100)),
                ('climber', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('order_status', models.CharField(max_length=100)),
                ('Order_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('life_cycle', models.CharField(max_length=100)),
                ('old', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='oder_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seedings', models.IntegerField()),
                ('inside_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_app.order')),
            ],
        ),
    ]
